# Generated by Django 5.0.1 on 2024-03-10 06:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_institutioncode_institution_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 3, 10, 15, 25, 56, 992698))),
                ('recipient_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientcode', to=settings.AUTH_USER_MODEL)),
                ('user_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercode', to='accounts.institutioncode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room',
                'unique_together': {('user_code', 'recipient_code')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2024, 3, 10, 15, 25, 56, 992698))),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
