# Generated by Django 5.0.1 on 2024-03-10 07:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_institutioncode_options'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 16, 51, 27, 801543)),
        ),
        migrations.AlterField(
            model_name='room',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 16, 51, 27, 801543)),
        ),
        migrations.AlterField(
            model_name='room',
            name='recipient_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipientcode', to='accounts.institutioncode'),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
