# Generated by Django 5.0.1 on 2024-03-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_institutioncode_institution_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutioncode',
            options={'ordering': ('institution_name',)},
        ),
    ]
